export const LESSON_ONE_MAP_CONFIG = {
  lessonKey: "tutorial",
  lessonTitle: "Tutorial: First Compile Trial",
  subtitle:
    "Kai learns the controls and first coding habits before entering Barangay Malumay.",

  stages: [
    {
      id: "stage-1",
      title: "Stage 1 - First Compile Trial",
      subtitle: "movement, inputs, counts, and precision",
      x: 50,
      y: 10,
    },
    {
      id: "stage-2",
      title: "Stage 2 - Barangay Malumay",
      subtitle: "arrays, indexes, and warding grids",
      x: 50,
      y: 50,
    },
  ],

  nodes: [
    {
      id: "tutorial-level-1",
      levelNumber: 1,
      title: "The Awakening",
      x: 12,
      y: 35,
    },
    {
      id: "tutorial-level-2",
      levelNumber: 2,
      title: "What Is Your Name?",
      x: 28,
      y: 28,
    },
    {
      id: "tutorial-level-3",
      levelNumber: 3,
      title: "Voices of the Village",
      x: 45,
      y: 35,
    },
    {
      id: "tutorial-level-4",
      levelNumber: 4,
      title: "The Coin Keeper",
      x: 62,
      y: 28,
    },
    {
      id: "tutorial-level-5",
      levelNumber: 5,
      title: "Potion Measure",
      x: 80,
      y: 35,
    },
    {
      id: "arrays-level-1",
      levelNumber: 6,
      title: "Lanterns of Malumay",
      x: 12,
      y: 77,
    },
    {
      id: "arrays-level-2",
      levelNumber: 7,
      title: "Stolen Supplies",
      x: 28,
      y: 70,
    },
    {
      id: "arrays-level-3",
      levelNumber: 8,
      title: "Road of Santelmo",
      x: 45,
      y: 77,
    },
    {
      id: "arrays-level-4",
      levelNumber: 9,
      title: "Midnight Inventory",
      x: 62,
      y: 70,
    },
    {
      id: "arrays-level-5",
      levelNumber: 10,
      title: "Warding Tile Grid",
      x: 80,
      y: 77,
    },
    {
      id: "arrays-level-6",
      levelNumber: 11,
      title: "Branching Path Map",
      x: 92,
      y: 70,
    },
    {
      id: "arrays-level-7",
      levelNumber: 12,
      title: "Kapre's Name Tags",
      x: 92,
      y: 86,
    },
  ],

  connections: [
    { fromId: "tutorial-level-1", toId: "tutorial-level-2" },
    { fromId: "tutorial-level-2", toId: "tutorial-level-3" },
    { fromId: "tutorial-level-3", toId: "tutorial-level-4" },
    { fromId: "tutorial-level-4", toId: "tutorial-level-5" },
    { fromId: "tutorial-level-5", toId: "arrays-level-1" },
    { fromId: "arrays-level-1", toId: "arrays-level-2" },
    { fromId: "arrays-level-2", toId: "arrays-level-3" },
    { fromId: "arrays-level-3", toId: "arrays-level-4" },
    { fromId: "arrays-level-4", toId: "arrays-level-5" },
    { fromId: "arrays-level-5", toId: "arrays-level-6" },
    { fromId: "arrays-level-6", toId: "arrays-level-7" },
  ],
};
