export const LESSON_ONE_MAP_CONFIG = {
  lessonKey: "variables-and-data-types",
  lessonTitle: "Variables and Data Types - The Castle of Syntax",
  subtitle:
    'A knight apprentice learning "code magic" to reach the castle gate.',
  stages: [
    {
      id: "stage-1",
      title: "Stage 1",
      subtitle: "Castle Grounds (Mastering Variables)",
      x: 50,
      y: 9,
    },
    {
      id: "stage-2",
      title: "Stage 2",
      subtitle: "Hall of Types (Exploring Data Types)",
      x: 50,
      y: 49,
    },
  ],
  nodes: [
    {
      id: "lesson1-level-1",
      levelNumber: 1,
      title: "The Awakening",
      x: 13,
      y: 26,
      rotation: -8,
    },
    {
      id: "lesson1-level-2",
      levelNumber: 2,
      title: "First Declarations",
      x: 30,
      y: 23,
      rotation: 7,
    },
    {
      id: "lesson1-level-3",
      levelNumber: 3,
      title: "Stone of Strings",
      x: 47,
      y: 26,
      rotation: -5,
    },
    {
      id: "lesson1-level-4",
      levelNumber: 4,
      title: "Torch of Values",
      x: 64,
      y: 23,
      rotation: 6,
    },
    {
      id: "lesson1-level-5",
      levelNumber: 5,
      title: "Twin Gates",
      x: 81,
      y: 26,
      rotation: -8,
    },
    {
      id: "lesson1-level-6",
      levelNumber: 6,
      title: "Hall of Numbers",
      x: 18,
      y: 74,
      rotation: 7,
    },
    {
      id: "lesson1-level-7",
      levelNumber: 7,
      title: "Potion of Truth",
      x: 35,
      y: 67,
      rotation: -5,
    },
    {
      id: "lesson1-level-8",
      levelNumber: 8,
      title: "Rune of Letters",
      x: 53,
      y: 79,
      rotation: 6,
    },
    {
      id: "lesson1-level-9",
      levelNumber: 9,
      title: "Whispering Scope",
      x: 70,
      y: 67,
      rotation: -7,
    },
    {
      id: "lesson1-level-10",
      levelNumber: 10,
      title: "Echo of Variables",
      x: 85,
      y: 75,
      rotation: 8,
    },
  ],
  connections: [
    { fromId: "lesson1-level-1", toId: "lesson1-level-2" },
    { fromId: "lesson1-level-2", toId: "lesson1-level-3" },
    { fromId: "lesson1-level-3", toId: "lesson1-level-4" },
    { fromId: "lesson1-level-4", toId: "lesson1-level-5" },
    { fromId: "lesson1-level-6", toId: "lesson1-level-7" },
    { fromId: "lesson1-level-7", toId: "lesson1-level-8" },
    { fromId: "lesson1-level-8", toId: "lesson1-level-9" },
    { fromId: "lesson1-level-9", toId: "lesson1-level-10" },
  ],
};
