const CANONICAL_LESSON_ORDER = Object.freeze([
  "tutorial",
  "arrays",
  "functions",
  "functions-with-arrays",
  "final",
]);

const ASSESSMENT_GATED_LESSON_KEYS = Object.freeze([
  "arrays",
  "functions",
  "functions-with-arrays",
]);

const LESSON_NEXT_ACTIONS = Object.freeze({
  COMPLETE_PREREQUISITE_LESSON: "COMPLETE_PREREQUISITE_LESSON",
  TAKE_PRE: "TAKE_PRE",
  RESUME_PRE: "RESUME_PRE",
  PLAY_GAME: "PLAY_GAME",
  TAKE_POST: "TAKE_POST",
  RESUME_POST: "RESUME_POST",
  RETRY_POST: "RETRY_POST",
  POST_RECOVERY_REQUIRED: "POST_RECOVERY_REQUIRED",
  LESSON_COMPLETE: "LESSON_COMPLETE",
});

const PROGRESSION_DENIAL_REASONS = Object.freeze({
  LESSON_PREREQUISITE_REQUIRED: "LESSON_PREREQUISITE_REQUIRED",
  PRE_ASSESSMENT_REQUIRED: "PRE_ASSESSMENT_REQUIRED",
  GAME_INCOMPLETE: "GAME_INCOMPLETE",
});

module.exports = {
  CANONICAL_LESSON_ORDER,
  ASSESSMENT_GATED_LESSON_KEYS,
  LESSON_NEXT_ACTIONS,
  PROGRESSION_DENIAL_REASONS,
};
