const { LEVEL_HINTS } = require("./levelHintCatalog");

const profile = (positive, location, reminder, nextAction, strongerFocus, supportedFailureCodes) =>
  Object.freeze({ positive, location, reminder, nextAction, strongerFocus, supportedFailureCodes });

const LEVEL_HINT_PROFILES = Object.freeze({
  "tutorial-level-1": profile("You kept the prepared movement exercise in place.", "the steps declaration and the value assigned to it", "An int stores a whole number, and the scene distance must be counted in walkable spaces.", "Count the spaces again, then change only the value assigned to steps.", "Trace each walkable tile from Kai to the portal and compare that count with steps.", ["WRONG_VARIABLE", "WRONG_TYPE", "WRONG_VALUE", "INCOMPLETE_SOLUTION"]),
  "tutorial-level-2": profile("The program already has the gatekeeper call ready.", "the myName declaration inside Main", "C# text uses string, double quotes, and exact capitalization.", "Compare the declared name character by character with the name shown in the dialogue.", "Check the type, variable name, quotation marks, spelling, and capital letter separately.", ["WRONG_VARIABLE", "WRONG_TYPE", "WRONG_VALUE", "INCOMPLETE_SOLUTION"]),
  "tutorial-level-3": profile("You are working in the correct section where the villagers' voices belong.", "the voice1, voice2, and voice3 declarations", "Each villager needs a separate string containing at least one character.", "Check each declaration one at a time for its name, type, and non-empty quoted value.", "Mark off all three voice variables and confirm none contains only an empty pair of quotes.", ["WRONG_VARIABLE", "WRONG_TYPE", "WRONG_VALUE", "INCOMPLETE_SOLUTION"]),
  "tutorial-level-4": profile("The challenge only needs one whole-number value.", "the coins declaration in Main", "The value must match the toll sign exactly; extra variables do not help.", "Read the sign again and update only the initializer for coins.", "Compare the number on the sign directly with the number after the equals sign.", ["WRONG_VARIABLE", "WRONG_TYPE", "WRONG_VALUE", "INCOMPLETE_SOLUTION"]),
  "tutorial-level-5": profile("You identified that the seal uses a numeric measurement.", "the type and initializer of measurement", "A value with a fractional part needs a decimal-capable type such as double.", "Keep the correct variable name and compare both the type and full decimal value with the seal.", "Verify the digits on both sides of the decimal point before running again.", ["WRONG_VARIABLE", "WRONG_TYPE", "WRONG_VALUE", "INCOMPLETE_SOLUTION"]),
  "arrays-level-1": profile("You are solving the challenge with an array, which is the intended structure.", "the lanterns declaration and the order inside its initializer", "Array elements keep the left-to-right order in which they are written.", "Read the four scene markers from left to right and compare them position by position.", "Number the four initializer positions, then match one scene marker to each position.", ["WRONG_VARIABLE", "WRONG_ARRAY_TYPE", "WRONG_ARRAY_VALUES", "INCOMPLETE_SOLUTION"]),
  "arrays-level-2": profile("Using one collection for the supplies is the right approach.", "the supplies array's type, name, quotes, and item order", "Every string element needs double quotes, and array order matters.", "Compare each crate label with the element in the same left-to-right position.", "Check the three elements individually for spelling, quotes, and sequence.", ["WRONG_VARIABLE", "WRONG_ARRAY_TYPE", "WRONG_ARRAY_VALUES", "INCOMPLETE_SOLUTION"]),
  "arrays-level-3": profile("Your submission has reached the array-selection part of the challenge.", "the flames initializer and the index inside the attack assignment", "C# arrays use zero-based positions, and the target must be selected through the array rather than typed directly.", "Label the positions starting at 0, locate the boss value, and use that position in the access expression.", "Write 0, 1, 2, and 3 above the four flames, then compare the boss position with the index in attack.", ["WRONG_VARIABLE", "WRONG_ARRAY_VALUES", "WRONG_ARRAY_INDEX", "HARDCODED_RESULT", "INCOMPLETE_SOLUTION"]),
  "arrays-level-4": profile("You are using an inventory collection for the three items.", "the inventory order and the index used for selectedItem", "The first array position is 0, so visual item numbers and indexes differ by one.", "Count the inventory positions from zero and make selectedItem read from the key's position.", "Annotate the three items with indexes 0 through 2 and inspect only the expression assigned to selectedItem.", ["WRONG_VARIABLE", "WRONG_ARRAY_VALUES", "WRONG_ARRAY_INDEX", "HARDCODED_RESULT", "INCOMPLETE_SOLUTION"]),
  "arrays-level-5": profile("A rectangular array is the intended way to represent this rune board.", "the ward type, row sizes, and row-by-row rune values", "In int[,], the first coordinate represents a row and every row must have the same number of columns.", "Compare the scene with the initializer one complete row at a time.", "Draw a three-cell checklist for each row and verify the rune encoding in all nine positions.", ["WRONG_VARIABLE", "WRONG_ARRAY_TYPE", "WRONG_ARRAY_DIMENSIONS", "WRONG_ARRAY_VALUES", "INCOMPLETE_SOLUTION"]),
  "arrays-level-6": profile("Representing checkpoints as a grid is the correct model.", "the pathMap rows and columns", "Each column is one checkpoint and should contain exactly one safe-height marker.", "Check each column from left to right and confirm its marker is in the correct row.", "Validate the grid column by column: one safe marker and two unsafe markers at every checkpoint.", ["WRONG_VARIABLE", "WRONG_ARRAY_TYPE", "WRONG_ARRAY_DIMENSIONS", "WRONG_ARRAY_VALUES", "INCOMPLETE_SOLUTION"]),
  "arrays-level-7": profile("The names belong in one ordered array before they are checked.", "the for-loop header and the argument passed to CheckName", "A full traversal starts at index 0, stops before Length, and processes the current indexed element.", "Trace the first and last loop iterations and make sure both call CheckName with an array element.", "For the last valid index, evaluate the loop condition and confirm the body still runs once for that name.", ["WRONG_ARRAY_VALUES", "MISSING_REQUIRED_CONSTRUCT", "WRONG_LOOP_BOUNDS", "WRONG_ARRAY_INDEX", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "arrays-level-8": profile("The jar colors can be scanned reliably from one ordered array.", "the loop bounds and the value passed to ScanJar", "The scan method needs jars at the current index on every iteration.", "Check that the loop visits the first through last valid indexes and passes one element each time.", "Simulate the index values on paper and write down which jar each ScanJar call receives.", ["WRONG_ARRAY_VALUES", "MISSING_REQUIRED_CONSTRUCT", "WRONG_LOOP_BOUNDS", "WRONG_ARRAY_INDEX", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-level-1": profile("You are separating a reusable action from Main.", "the StartRitual definition and its invocation in Main", "Defining a method creates the action; a separate call runs it.", "Check first for the no-parameter void definition, then for exactly one call inside Main.", "Find two distinct pieces: the method header outside Main and the invocation inside Main.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-level-2": profile("The RingBell action is already defined for you.", "Main, where the prepared method should be invoked", "A parameterless method call needs the exact name, parentheses, and a statement ending.", "Call the existing method once without creating another definition.", "Look only inside Main and verify there is one executable RingBell invocation.", ["MISSING_METHOD_CALL", "WRONG_ARGUMENT", "INCOMPLETE_SOLUTION"]),
  "functions-level-3": profile("You are building a reusable action for the warding flame.", "the LightFlame method header and the call in Main", "This action has no returned value and no input parameters.", "Verify the definition uses void with empty parentheses, then invoke it from Main.", "Separate definition from execution: one method outside Main, one call inside Main.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-level-4": profile("A dedicated method is the right structure for the shrine action.", "the SealShrine definition and its call site", "A no-input action uses an empty parameter list and void return type.", "Check the exact method name and then confirm Main actually invokes it.", "Inspect the method header and Main independently; both pieces are required.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-level-5": profile("You are using a method to produce the oracle code.", "GetCode's return type and return statement, then the assignment in Main", "A result-producing method must return a value, and Main must use the method call rather than a typed final answer.", "Follow the value from the return statement into the variable initialized in Main.", "Trace one path: method call, returned integer, then the code variable receiving that integer.", ["MISSING_METHOD", "WRONG_RETURN_TYPE", "WRONG_RETURN_VALUE", "HARDCODED_RESULT", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-level-6": profile("A method is the right place to provide the safe direction.", "GetSafePath's return type and the path assignment in Main", "Returning text requires string, a return statement, and a caller that stores the result.", "Compare the direction in the scene with the returned text, then trace the method call into path.", "Verify the returned word inside the method before checking that Main stores the call result.", ["MISSING_METHOD", "WRONG_RETURN_TYPE", "WRONG_RETURN_VALUE", "HARDCODED_RESULT", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-level-7": profile("You are using the prepared offering method instead of rebuilding it.", "the argument inside the PlaceOffering call in Main", "A string argument must be quoted and becomes the method's item parameter.", "Compare the shrine request with the single value passed to the method.", "Inspect only the text between the call parentheses and verify its spelling and quotes.", ["WRONG_ARGUMENT", "MISSING_METHOD_CALL", "WRONG_METHOD_SIGNATURE", "INCOMPLETE_SOLUTION"]),
  "functions-level-8": profile("The prepared ThrowSalt method is the correct action to use.", "the argument inside the ThrowSalt call", "The amount parameter expects one whole number derived from the scene markers.", "Count the markers and compare that number with the call argument.", "Follow the numbered markers to the target, then inspect only the value between the call parentheses.", ["WRONG_ARGUMENT", "MISSING_METHOD_CALL", "WRONG_TYPE", "INCOMPLETE_SOLUTION"]),
  "functions-level-9": profile("You are modeling the power calculation as a reusable method.", "the two parameters, the returned expression, and the stored call result", "The result should be calculated from both parameter variables rather than hardcoded.", "Trace both arguments into their parameters and check the operator used between them.", "Substitute the displayed inputs into the return expression by hand and compare the result with the required power.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "WRONG_RETURN_TYPE", "WRONG_RETURN_VALUE", "HARDCODED_RESULT", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-level-10": profile("A two-input method is the right structure for the healing calculation.", "Heal's parameters, arithmetic operator, and the assignment in Main", "The return expression must use the parameter variables and the operation described by the challenge.", "Substitute the herb and water inputs into your expression and verify the operation.", "Calculate your current return expression with the displayed inputs; if it misses the target, reconsider the operator.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "WRONG_RETURN_TYPE", "WRONG_RETURN_VALUE", "HARDCODED_RESULT", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-level-11": profile("You are using a method that can call itself, which is the intended technique.", "BuildStairs's stopping condition, smaller recursive call, and CreateStep order", "Recursion needs a reachable base case and each call must move closer to it.", "Trace the step value across calls and ensure it decreases before the stair action runs.", "Write the sequence of step values until zero, then trace the order in which CreateStep runs as calls return.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "WRONG_RECURSIVE_BASE_CASE", "WRONG_RECURSIVE_STEP", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-with-arrays-level-1": profile("You are combining an array with a reusable method.", "LightLanterns's parameter, the lanterns initializer, and the call in Main", "An int[] parameter receives the entire array variable in one argument.", "Check the method signature first, then the array values, then the call that passes the whole array.", "Confirm the same array variable flows from its declaration into the single method parameter.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "WRONG_ARRAY_VALUES", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-with-arrays-level-2": profile("The prepared array is ready to be examined by a counting method.", "the counter, full traversal, condition, increment, return, and stored result", "A conditional count starts at zero, visits each element, increments only on a match, and returns after the loop.", "Trace one safe and one cursed value through your loop to see whether the counter changes correctly.", "Make a six-row trace table with index, current value, and count; the first mismatch reveals the faulty step.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "MISSING_COUNTER", "WRONG_LOOP_BOUNDS", "WRONG_CONDITION", "MISSING_INCREMENT", "WRONG_RETURN_VALUE", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-with-arrays-level-3": profile("A rectangular grid can be passed as one method argument.", "RestoreGrid's int[,] parameter, the grid shape and values, and the call", "The method parameter and the declared argument must use the same rectangular array type.", "Compare the scene row by row, then confirm the whole grid variable is passed once.", "Check the pipeline in order: matching int[,] types, complete grid initializer, then one whole-array call.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "WRONG_ARRAY_TYPE", "WRONG_ARRAY_DIMENSIONS", "WRONG_ARRAY_VALUES", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "functions-with-arrays-level-4": profile("The existing grid provides all the data needed for a nested traversal.", "the row loop, column loop, cell condition, increment, return, and assignment", "Each array dimension needs its own bound, and the condition must inspect the current row-column cell.", "Trace the first row across every column before moving to the next row.", "Create a row-column-count trace for several cells and identify where your loop or condition diverges.", ["MISSING_METHOD", "WRONG_METHOD_SIGNATURE", "MISSING_COUNTER", "WRONG_LOOP_BOUNDS", "WRONG_ARRAY_INDEX", "WRONG_CONDITION", "MISSING_INCREMENT", "WRONG_RETURN_VALUE", "MISSING_METHOD_CALL", "INCOMPLETE_SOLUTION"]),
  "final-level-1": profile("The final program is organized into the intended six seal phases.", "the first phase named by the validator", "Fixing phases in order prevents a later symptom from hiding an earlier requirement.", "Work only on the reported phase, verify its input and output, then run again.", "Trace the reported phase independently with its smallest example before reconnecting it in Main.", ["FINAL_PHASE_1", "FINAL_PHASE_2", "FINAL_PHASE_3", "FINAL_PHASE_4", "FINAL_PHASE_5", "FINAL_PHASE_6", "INCOMPLETE_SOLUTION"]),
});

const GLOBAL_FAILURE_GUIDANCE = Object.freeze({
  COMPILER_MISSING_SEMICOLON: ["The program cannot be checked yet because a statement appears to be missing its ending semicolon.", "C# statements such as declarations, assignments, returns, and method calls normally end with a semicolon.", "Inspect the reported or most recently edited statement and add its terminator before checking the challenge logic."],
  COMPILER_UNMATCHED_DELIMITER: ["The program cannot be checked yet because parentheses, brackets, or braces are not balanced.", "Every opening delimiter needs the matching closing delimiter in the correct nesting order.", "Start near the most recently edited block or expression and pair each opening symbol with its close."],
  COMPILER_UNKNOWN_NAME: ["The compiler cannot find a name used by the program.", "C# names are case-sensitive and must be declared before they are used in that scope.", "Compare the spelling and capitalization at the use site with the declaration."],
  COMPILER_TYPE_MISMATCH: ["The compiler found a value whose type does not fit its destination.", "Variables, parameters, and return values must receive compatible C# types.", "Compare the type on both sides of the reported assignment, argument, or return."],
  COMPILER_INVALID_METHOD_USAGE: ["The compiler cannot match this method call to the method's parameter list.", "A call must use the expected number and types of arguments in the declared order.", "Compare the call parentheses with the method signature one argument at a time."],
  COMPILER_ERROR: ["The program cannot run yet because the compiler found a problem.", "Compiler errors must be corrected before the challenge validator can judge the program's logic.", "Use the original compiler message to locate the line, then check names, types, delimiters, and statement endings."],
});

const FAILURE_GUIDANCE = Object.freeze({
  INCOMPLETE_SOLUTION: ["The required challenge structure is still incomplete.", "Starter comments mark the places where declarations, methods, calls, or calculations belong.", "Complete one missing requirement at a time, beginning with the first task instruction."],
  WRONG_VARIABLE: ["A declaration has the wrong variable name or an extra declaration.", "The validator connects the scene to specific prepared variable names.", "Compare each declared name with the task wording and remove unrelated declarations."],
  WRONG_TYPE: ["A value is being represented with the wrong C# type.", "The type must match whether the challenge expects whole numbers, decimal numbers, text, or an array.", "Identify the kind of value required, then correct the declaration type without changing unrelated code."],
  WRONG_VALUE: ["The declaration is present, but its assigned value does not match the scene requirement.", "A correct variable can still produce the wrong result when its initializer is off.", "Re-read the relevant sign or dialogue and compare it directly with the initializer."],
  WRONG_ARRAY_TYPE: ["The collection uses a different array shape from the one the challenge requires.", "A one-dimensional array, rectangular array, and jagged array are different C# types.", "Match the bracket notation in the task before checking the values."],
  WRONG_ARRAY_DIMENSIONS: ["The grid shape or row-column interpretation is incorrect.", "Rectangular arrays need the expected number of equal-length rows and columns.", "Count the visual rows and columns, then compare them with every initializer row."],
  WRONG_ARRAY_VALUES: ["The collection exists, but one or more elements are missing, out of order, or encoded incorrectly.", "Array positions preserve order, so each scene item must match the corresponding element.", "Compare the scene and initializer one position at a time instead of checking only the total items."],
  WRONG_ARRAY_INDEX: ["The program is looking at the wrong element or is not using the current indexed element.", "C# array indexes start at zero and must remain within the valid range.", "Label the element positions from zero and compare the target position with the access expression."],
  MISSING_REQUIRED_CONSTRUCT: ["The output or declarations may be partly present, but the required learning construct is missing.", "This challenge evaluates how the result is produced, not only the final value.", "Use the construct named in the task and move the repeated or reusable work into it."],
  WRONG_LOOP_BOUNDS: ["The traversal is likely starting, stopping, or advancing at the wrong point.", "A complete array loop normally begins at zero and stops before the relevant Length or GetLength value.", "Evaluate the loop header for the first and last valid indexes."],
  WRONG_CONDITION: ["The traversal structure is present, but the condition tests the wrong value or marker.", "The condition should inspect the current element and update the count only for the target case.", "Trace one matching and one non-matching element through the condition."],
  MISSING_COUNTER: ["The counting process has no correctly initialized accumulator.", "A count should begin before traversal and change only when the target condition is true.", "Create or correct the counter initialization, then follow it through the loop."],
  MISSING_INCREMENT: ["The target case is detected, but the counter is not increased in the correct block.", "The increment belongs inside the condition that identifies one matching element.", "Move or add the single-step counter update inside that conditional body."],
  MISSING_METHOD: ["The required method definition is missing or does not match the expected header.", "A method definition specifies its return type, exact name, and parameter list before its body.", "Compare the method header with the task, then keep it inside Program and outside Main."],
  WRONG_METHOD_SIGNATURE: ["The method exists, but its return type or parameters do not match the required contract.", "Callers and method definitions must agree on argument count, order, and types.", "Compare the signature and call side by side, one parameter at a time."],
  MISSING_METHOD_CALL: ["The method or value may be defined, but Main is not using it in the required way.", "A definition does not execute until it is called, and returned values must be stored when the task requires it.", "Find Main and trace the required method invocation and its result there."],
  WRONG_ARGUMENT: ["The method call is present, but its argument does not match the requested input.", "An argument supplies the value received by the method's corresponding parameter.", "Compare the scene value, its C# type, and the expression between the call parentheses."],
  WRONG_RETURN_TYPE: ["The method's declared return type does not match the value it must send back.", "Use void only for actions that return nothing; result-producing methods declare the result's type.", "Determine the required result kind, then align the method header and return statement."],
  WRONG_RETURN_VALUE: ["The method structure is mostly present, but the returned calculation or value is incorrect or missing.", "A return statement sends the method's result to its caller and should use the required inputs.", "Trace the expected result backward from Main to the expression after return."],
  HARDCODED_RESULT: ["The final value may look right, but it bypasses the method or array operation this challenge is designed to practice.", "The validator requires the result to flow from the requested construct rather than a copied literal.", "Replace the typed final answer with the relevant method call or indexed access."],
  WRONG_RECURSIVE_BASE_CASE: ["The recursive method does not yet have a safe stopping condition.", "A reachable base case must return before another recursive call is made.", "Trace the parameter toward its smallest case and stop there."],
  WRONG_RECURSIVE_STEP: ["The recursive chain does not reliably move toward its stopping case or performs the action in the wrong order.", "Each recursive call must use a smaller problem, and statement order controls the unwind sequence.", "Write the parameter values for successive calls, then trace the actions as those calls return."],
  FINAL_PHASE_1: ["The first seal's source array no longer matches the arena symbols.", "Later phases depend on the prepared symbol sequence remaining intact.", "Restore the phase-one data from the scene before debugging later methods."],
  FINAL_PHASE_2: ["The corrupted-symbol counting phase is incomplete.", "This phase needs a counter, a full traversal, a test for the corrupted marker, and a returned result.", "Trace every symbol and record when the counter should change."],
  FINAL_PHASE_3: ["The repair action is not both defined with its index parameter and invoked for the damaged seal.", "A parameterized action needs a matching method header and call argument.", "Compare the corrupted position found in phase one with the RepairSymbol call."],
  FINAL_PHASE_4: ["The ward calculation is not returning the combination of both inputs.", "The result must be derived from the method parameters, not a final literal.", "Substitute simple values into the return expression to verify its operator."],
  FINAL_PHASE_5: ["The moon-grid method is not visiting every row and column before returning.", "A rectangular grid requires nested loops using dimension 0 and dimension 1.", "Trace the row-column pairs and confirm each cell is accessed."],
  FINAL_PHASE_6: ["The eclipse recursion or the final connections in Main are incomplete.", "The recursion needs a zero-phase stop and a call that reduces the phase each time.", "Trace the phase values to zero, then verify Main invokes every required result-producing step."],
});

const getLevelHintProfile = (levelKey) => LEVEL_HINT_PROFILES[levelKey] ?? null;

const getFallbackHint = (levelKey) => {
  const definition = LEVEL_HINTS[levelKey];
  const profileDefinition = getLevelHintProfile(levelKey);
  if (!definition || !profileDefinition) return null;
  return `${profileDefinition.positive}\n\nThe validator could not narrow this attempt to a known mistake.\n\nLook at: ${profileDefinition.location}.\n\n${profileDefinition.reminder}\n\nNext: ${profileDefinition.nextAction}`;
};

module.exports = {
  FAILURE_GUIDANCE,
  GLOBAL_FAILURE_GUIDANCE,
  LEVEL_HINT_PROFILES,
  getFallbackHint,
  getLevelHintProfile,
};
